### ISSUE TITLE
The link for getting API key is not working .(https://developer.echonest.com/)

### ISSUE THREAD

**Issue by vishrutkohli** [echonest/remix#53]

**Comment by ddesroches** [comment]
vishrutkohli,
Sorry, but The Echo Nest API was taken down a while ago.

**Comment by vishrutkohli** [comment]
Is there any way to use it now ?

**Comment by ddesroches** [comment]
Remix is dead, I'm afraid, since The Echo Nest analyze API is not available. Try https://github.com/algorithmic-music-exploration/amen. This is the package recommended in the Remix README. It was built by an Echo Nest alumnus, @tkell, based on Remix features.
